import{a as C,S as E,i as m}from"./assets/vendor-D3PmPE7A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const $="https://pixabay.com",q="/api",P="48962354-d02229266f1321f72919e6f30";async function p(o,t,a){const r=new URLSearchParams({key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:a}),e=`${$}${q}?${r}`;return(await C.get(e)).data}let d;const u=document.querySelector(".gallery");function w(o,t=!1){t||(u.innerHTML="");const a=o.map(r=>`<li class="gallery-item">
            <a class='gallery-link' href="${r.largeImageURL}">
              <img class="li-img"
              src="${r.webformatURL}" 
              alt="${r.tags}"/> 
              <div class="li-text">
                <table class="table">
                    <tr><td>Likes</td><td>Views</td><td>Comments</td><td>Downloads</td></tr>
                    <tr><td>${r.likes}</td><td>${r.views}</td><td>${r.comments}</td><td>${r.downloads}</td></tr>
                </table>
              </div>
            </a>
        </li>`).join("");u.insertAdjacentHTML(t?"beforeend":"afterbegin",a),d?d.refresh():d=new E(".gallery a",{captionsData:"alt",captionDelay:250})}function L(){u.innerHTML=""}function T(){L(),m.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"#EF4040"})}const R=document.querySelector(".form"),y=document.querySelector(".input-search"),b=document.querySelector(".wait-msg"),g=document.querySelector(".load-more-btn");let i="",n=1;const l=40;let f=0;R.addEventListener("submit",x);g.addEventListener("click",H);async function x(o){if(o.preventDefault(),i=y.value.trim(),n=1,!i){h("Input search string");return}y.value="",L(),M(),S();try{const t=await p(i,n,l);if(f=t.totalHits,!t.hits.length){T();return}w(t.hits),n*l<f&&F()}catch(t){console.error(t),h("Failed to load images. Try again later.")}finally{v()}}async function H(){n+=1,S();try{const o=await p(i,n,l);w(o.hits,!0),I(),n*l>=f&&(M(),m.show({position:"topRight",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"#EF4040",timeout:5e3}))}catch(o){console.error(o),h("Failed to load more images. Try again later.")}finally{v()}}function S(){b.innerHTML='Loading... <span class="loader"></span>'}function v(){b.textContent=""}function F(){g.style.display="block"}function M(){g.style.display="none"}function I(){setTimeout(()=>{const o=document.querySelector(".gallery-item");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}},300)}function h(o){m.show({backgroundColor:"#EF4040",messageColor:"#fff",close:!0,position:"topRight",title:"Error",titleColor:"#fff",titleSize:"16px",message:o})}
//# sourceMappingURL=index.js.map
